"""empty message

Revision ID: 20dc901615fd
Revises: 1b470b9d01e5
Create Date: 2021-07-28 08:21:14.311419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dc901615fd'
down_revision = '1b470b9d01e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast', 'role')
    # ### end Alembic commands ###
